development: 
  theme_id: "292323349"
  password: 4689fb2155eaa42cc47c2bebbb8a20c8
  store: nut-tag.myshopify.com
  ignores:
    - myignores
  ignore_files:
    - config/settings_data.json
    - "*.png"
    - "*.jpg"
    - "*.gif"
    - "*.svg"

staging:
  theme_id: "292323349"
  password: 4689fb2155eaa42cc47c2bebbb8a20c8
  store: nut-tag.myshopify.com

production:
  theme_id: "292323349"
  password: 4689fb2155eaa42cc47c2bebbb8a20c8
  store: nut-tag.myshopify.com
  timeout: 60s
  readonly: true